name: BUILD UTILS
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.18.1'
      - name: Check local/remote pkg versions
        run: node ./.github/willPublish.js
      - name: Installing dependencies
        run: yarn install
      - name: Building project
        run: yarn build
      - name: Running tests
        run: yarn test
